// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB--l19cCzUrmVY6X18IkUsXLqJRGlg2TY',
    appId: '1:680739651296:android:d07fe868f6f7352f459a85',
    messagingSenderId: '680739651296',
    projectId: 'devmind-207f0',
    storageBucket: 'devmind-207f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBygSuFuIPEAPHKKW6zNsWbEB5pdC7Xma4',
    appId: '1:680739651296:ios:8f94c29cf2836138459a85',
    messagingSenderId: '680739651296',
    projectId: 'devmind-207f0',
    storageBucket: 'devmind-207f0.firebasestorage.app',
    iosBundleId: 'com.hrilin.devmind',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRpE5kvNN16IxlyNJLCAlMJv8EnJl7RE0',
    appId: '1:680739651296:web:1e8edb4122bb7eed459a85',
    messagingSenderId: '680739651296',
    projectId: 'devmind-207f0',
    authDomain: 'devmind-207f0.firebaseapp.com',
    storageBucket: 'devmind-207f0.firebasestorage.app',
    measurementId: 'G-B25HSV4BR5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBygSuFuIPEAPHKKW6zNsWbEB5pdC7Xma4',
    appId: '1:680739651296:ios:8f94c29cf2836138459a85',
    messagingSenderId: '680739651296',
    projectId: 'devmind-207f0',
    storageBucket: 'devmind-207f0.firebasestorage.app',
    iosBundleId: 'com.hrilin.devmind',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRpE5kvNN16IxlyNJLCAlMJv8EnJl7RE0',
    appId: '1:680739651296:web:1cabf8e6782099e6459a85',
    messagingSenderId: '680739651296',
    projectId: 'devmind-207f0',
    authDomain: 'devmind-207f0.firebaseapp.com',
    storageBucket: 'devmind-207f0.firebasestorage.app',
    measurementId: 'G-VLTEYCX1FP',
  );

}